import = [
    # "~/.config/alacritty/themes/themes/synthwave_84.toml"
    # "~/.config/alacritty/themes/themes/wombat.toml"
    # "~/.config/alacritty/themes/themes/terafox.toml"
    # "~/.config/alacritty/themes/themes/rose_pine_moon.toml"
    # "~/.config/alacritty/themes/themes/citylights.toml"
    # "~/.config/alacritty/themes/themes/breeze.toml"
    "~/.config/alacritty/themes/themes/ayu_mirage.toml"
]

[font]
size = 9.5

[font.bold]
family = "CodeNewRoman Nerd Font"
style = "Bold"

[font.italic]
family = "CodeNewRoman Nerd Font"
style = "Italic"

[font.normal]
family = "CodeNewRoman Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = true
option_as_alt = "OnlyLeft"

opacity = 0.9
blur = true

[window.padding]
x = 0
y = 0
