" ---------------------------------------------------
"		      General
" ---------------------------------------------------

set background=light

set encoding=UTF-8

" who would care about vi compatibility anyway
set nocompatible

" prevent entering Ex mode
nnoremap Q <nop>

" highlighting settings
set hls
nnoremap <esc> :noh<return><esc>
nnoremap <esc>^[ <esc>^[
set smartcase

" settings regarding whether to use relative or absolute line numbers
set number relativenumber
:au FocusLost * :set norelativenumber number
:au FocusGained * :set number relativenumber
autocmd InsertEnter * :set norelativenumber number
autocmd InsertLeave * :set number relativenumber

" syntax highlighting
syntax on

" Show error at over 80 characters (kernel dev)
highlight ColorColumn ctermbg=magenta
call matchadd('ColorColumn', '\%81v', 100)

" One tab 8 characters wide
set tabstop=8
set shiftwidth=8

" Do not expand comments on new line
au FileType * set fo-=c fo-=r fo-=o

" Stop messing with newlines at the end of file all the time
set nofixendofline

" Paste directly from keyboard using p
set clipboard=unnamed

" Cursorline
set cursorline

" ---------------------------------------------------
"		       Keymaps
" ---------------------------------------------------

nnoremap <C-k> :cprev<CR>zz
nnoremap <C-j> :cnext<CR>zz
nnoremap ]q :cnext<cr>
nnoremap [q :cprev<cr>
nnoremap ]Q :clast<cr>
nnoremap [Q :cfirst<cr>

nnoremap ]b :bnext<cr>
nnoremap [b :bprev<cr>
nnoremap ]B :blast<cr>
nnoremap [B :bfirst<cr>

" ---------------------------------------------------
"		    Leader keymaps
" ---------------------------------------------------

" set leader
let mapleader = ","

" <leader>v - open .vimrc
nmap <leader>v :e $MYVIMRC<CR>

" <leader>n - absolute, relative or no line number switch
function! NumberToggle()
  if(&relativenumber == 1)
    set norelativenumber number
  else
    if(&number == 1)
      set nonumber norelativenumber
    else
      set number relativenumber
    endif
  endif
endfunc
nnoremap <leader>n :call NumberToggle()<cr>

" <leader>p - show path to current file
nmap <leader>p :echo expand('%:p')<cr>

" <leader>s - split lines by whitespace
nmap <leader>s :s/\s\+/\r/g<cr>:noh<cr><cr>

